version: "3.5"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: "elasticsearch"
    environment:
      - cluster.name=microservice-monitoring
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      #- ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      #- xpack.security.enabled=$ELASTIC_SECURITY
      - xpack.monitoring.collection.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw              # Persistence data
    restart: on-failure
    

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    container_name: "logstash"
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: "kibana"
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    container_name: "filebeat"
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash

  comment-service:
    image: ibm/comment-service:latest
    container_name: "comment-service"
    ports:
      - "8002:8002"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  feeds-service:
    image: ibm/feeds-service:latest
    container_name: "feeds-service"
    ports:
      - "8001:8001"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"